---
title: "Test(?) file for the package"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggwaffle)
library(gganimate)
library(pgog)
library(patchwork)
library(animation)
```


```{r}
data("small_salary_100")
```



# animate_group_by_sanddance


```{r}
animate_group_by_sanddance(small_salary, Degree)

animate_group_by_sanddance(small_salary, Degree, Work)
```


# animate_summarize_mean_sanddance

```{r}
grouped_salaries <- small_salary %>% group_by(Degree)
animate_summarize_mean_sanddance(grouped_salaries, Salary, nframes = 5)

grouped_salaries2 <- small_salary %>% group_by(Degree, Work) 
animate_summarize_mean_sanddance(grouped_salaries2, Salary, nframes = 5)
```

## By steps

```{r}
animate_summarize_mean_sanddance(grouped_salaries2, Salary, nframes = 5, output = "first")

animate_summarize_mean_sanddance(grouped_salaries2, Salary, nframes = 5, output = "second")
```


# GIF export

## By step

```{r}
saveGIF({
  small_salary %>%
    animate_group_by_sanddance(Degree, nframes = 30, is_last = TRUE) 
}, movie.name="Degree_two_colors_groupby.gif", interval = 0.1, 
ani.width = 500, ani.height = 350, ani.res = 100)

```

```{r}
saveGIF({
  small_salary %>%
    group_by(Degree) %>%
    animate_summarize_mean_sanddance(Salary, nframes = 30)
}, movie.name="Degree_two_colors_summarizemean.gif", interval = 0.1, 
ani.width = 500, ani.height = 350, ani.res = 100)

```

```{r}
saveGIF({
  small_salary %>%
    animate_group_by_sanddance(Degree, Work, nframes = 30)
}, movie.name="Work_Degree_two_colors_groupby.gif", interval = 0.1, ani.width = 500, ani.height = 350, ani.res = 100)

```


```{r}
saveGIF({
  small_salary %>%
    group_by(Degree, Work) %>%
    animate_summarize_mean_sanddance(Salary, nframes = 30)
}, movie.name="Work_Degree_two_colors_summarizemean.gif", interval = 0.1, ani.width = 500, ani.height = 350,
 ani.res = 100)

```

## full movie

```{r}
saveGIF({
  small_salary %>%
    animate_group_by_sanddance(Degree, nframes = 30) %>%
    animate_summarize_mean_sanddance(Salary, nframes = 30)
}, movie.name="Degree_two_colors.gif", interval = 0.1, ani.width = 500, ani.height = 350, ani.res = 100)

```

```{r}
saveGIF({
  small_salary %>%
    animate_group_by_sanddance(Degree, Work, nframes = 30) %>%
    animate_summarize_mean_sanddance(Salary, nframes = 30)
}, movie.name="Work_Degree_two_colors.gif", interval = 0.1, ani.width = 500, ani.height = 350, ani.res= 100)

```


