---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# dmpkg

## Installation

First, download the zip file of the package source called `dmpkg_0.0.0.9007.tar.gz` 
from [this link](https://zenodo.org/record/4287448). 
Then run the code below and select the zip file you downloaded.

```{r, eval=FALSE}
install.packages(file.choose(), repos = NULL, type="source")
```

## Examples for Plot-based Datamations

```{r, eval=FALSE}
library(dmpkg)
library(animation)
library(tidyverse)
```


```{r, eval=FALSE}
degree_title_step1 <- "Step 1: Each dot shows one person\n            and each group shows degree type"
degree_title_step2 <- "Step 2: Next you plot the salary of each person\n            within each group"
degree_title_step3 <- "Step 3: Lastly you plot the average salary \n            of each group and zoom in"
work_degree_title_step1 <- "Step 1: Each dot shows one person and each group\n            shows degree type AND work setting"
```



```{r}
# temporary test 
test_pipe2 <- "small_salary %>% group_by(Degree, Work) %>% summarize(mean = mean(Salary))"

datamation_sanddance(test_pipe2, output = "Degree_Work_two_colors.gif")

test_pipe <- "small_salary %>% group_by(Degree) %>% summarize(mean = mean(Salary))"

datamation_sanddance(test_pipe, output = "Degree_two_colors.gif")
```


```{r, eval=FALSE}
# The command below takes 90 seconds to execute on my machine
saveGIF({
  small_salary %>%
    dmpkg::animate_group_by_sanddance(Degree, nframes = 30, 
                               titles = degree_title_step1) %>%
    dmpkg::animate_summarize_mean_sanddance(Salary, nframes = 30,
                                     titles = c(degree_title_step2, degree_title_step3))
}, movie.name="Degree_two_colors.gif", interval = 0.1, ani.width = 500, ani.height = 350, ani.res = 100)

# The command below takes 100 seconds to execute on my machine
saveGIF({
  small_salary %>%
    dmpkg::animate_group_by_sanddance(Degree, Work, nframes = 30, 
                               titles = work_degree_title_step1) %>%
    dmpkg::animate_summarize_mean_sanddance(Salary, nframes = 30,
                                     titles = c(degree_title_step2, degree_title_step3))
}, movie.name="Work_Degree_two_colors.gif", interval = 0.1, ani.width = 500, ani.height = 350, ani.res= 100)
```

## Examples for Table-based Datamations

```{r, eval=FALSE}
library(dmpkg)
library(tidyverse)

# The command below takes 20 seconds to execute on my machine
pipeline <- "small_salary_data %>% group_by(Degree)"
dmpkg::datamation_tibble(pipeline, output = "salary_group_degree.gif")

# The command below takes 40 seconds to execute on my machine
pipeline <- "mtcars %>% group_by(cyl)"
dmpkg::datamation_tibble(pipeline, output = "mtcars_group_cyl.gif")

# The command below takes 50 seconds to execute on my machine
pipeline <- "small_salary_data %>% group_by(Degree, Work) %>% summarize(Avg_Salary = mean(Salary))"
dmpkg::datamation_tibble(pipeline, output = "salary_group2_summarize_mean.gif")

# The command below takes 50 seconds to execute on my machine
pipeline <- "small_salary_data %>% group_by(Degree, Work) %>% summarize(Avg_Salary = mean(Salary))"
dmpkg::datamation_tibble(pipeline, output = "salary_group2_summarize_mean.gif",
                         titles = c("Grouping by Degree and Work", 
                                    "Calculating the Mean of Each Group"))
```
